const plugin = require("tailwindcss/plugin");

module.exports = {
  content: ["./src/**/*.{html,ts}"],
  purge: {
    //enabled:true,
    //content:['/apps/hope-dashboard/**/*.{html,ts}']
  },
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1441px",
      xl: "1600px",
      tablet: { max: "62rem" },
      phone: { max: "48rem" },
    },
    fontFamily: {
      display: ["lato", "sans-serif"],
      body: ["lato", "sans-serif"],
    },
    border: {
      "05": "0.5px",
    },
    borderRadius: {
      none: "0",
      sm: ".375rem",
      default: "2rem",
      md: "1rem",
      lg: "4rem",
      full: "9999rem",
      circle: "100%",
    },
    fontSize: {
      xxs: ".65rem",
      xs: ".75rem",
      sm: ".875rem",
      base: "16px",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      xxl: "1.75rem",
      "3xl": "2rem",
      "4xl": "2.5rem",
      "5xl": "2.85rem",
      "6xl": "3.75rem",
    },
    opacity: {
      0: "0",
      1: ".01",
      2: ".02",
      3: ".03",
      4: ".04",
      5: ".05",
      10: ".1",
      15: ".15",
      20: ".2",
      25: ".25",
      30: ".3",
      35: ".35",
      40: ".4",
      45: ".45",
      50: ".5",
      55: ".55",
      60: ".6",
      65: ".65",
      70: ".7",
      75: ".75",
      80: ".8",
      85: ".85",
      90: ".9",
      95: ".95",
      100: "1",
    },
    extend: {
      colors: {
        violet: {
          DEFAULT: "#2F288D",
          20: "#2F288D80",
          50: "#D9D5ED",
          100: "#A29EE3",
          200: "#7D76D8",
          300: "#574ECD",
          400: "#3C33B5",
          500: "#2F288D",
          550: "#F6F5FD",
          600: "#221D65",
          700: "#15113E",
          800: "#070616",
          900: "#000000",
          1000: "#F8F7FF",
        },
        green: {
          DEFAULT: "#0BB796",
          100: "#95F9E6",
          200: "#65F6DA",
          300: "#35F3CE",
          400: "#0EE7BD",
          500: "#0BB796",
          550: "#07B796",
          600: "#08876F",
          700: "#055747",
          800: "#022720",
          900: "#000000",
        },
        blue: {
          500: "#0B6EB7",
          550: "#07A9B7",
        },
        gray: {
          50: "#959496",
        },
        red: {
          DEFAULT: "#ff0000",
          50: "#E94469",
          80: "#F8C6D1",
          100: "#FAD9E0",
          200: "#F5ABBC",
          300: "#F07D98",
          400: "#EA5073",
          500: "#E5224F",
          600: "#BE163D",
          700: "#90112E",
          800: "#620C20",
          900: "#350611",
        },
        pink: {
          DEFAULT: "#B322FF",
          100: "#F9EEFF",
          200: "#E8BBFF",
          300: "#D688FF",
          400: "#C555FF",
          500: "#B322FF",
          600: "#9C00EE",
          700: "#7B00BB",
          800: "#590088",
          900: "#380055",
        },
        "ocean-blue": {
          DEFAULT: "#0B6EB7",
          100: "#95CFF9",
          200: "#65B8F6",
          300: "#35A2F3",
          400: "#0E8BE7",
          500: "#0B6EB7",
          600: "#085187",
          700: "#053457",
          800: "#021727",
          900: "#000000",
        },
        primary: {
          DEFAULT: "#080431",
          50: "#06062F",
          100: "#2815EC",
          200: "#1F10BE",
          300: "#170C8F",
          350: "#30288d",
          400: "#100860",
          500: "#080431",
          600: "#0e0857",
          700: "#000002",
          800: "#000000",
          900: "#000000",
        },
        yellow: {
          DEFAULT: "#FFBB22",
          100: "#FFFAEE",
          200: "#FFEABB",
          300: "#FFDA88",
          400: "#FFCB55",
          500: "#FFBB22",
          600: "#EEA500",
          700: "#BB8100",
          800: "#885E00",
          900: "#553B00",
        },
        "royal-blue": {
          DEFAULT: "#6258E8",
          100: "#FFFFFF",
          200: "#E0DEFB",
          300: "#B6B2F4",
          400: "#8C85EE",
          500: "#6258E8",
          600: "#382BE2",
          700: "#261AC0",
          800: "#1D1493",
          900: "#140E66",
        },
        purple: {
          50: "#D3D0FF9B",
          150: "#2F288D66",
        },
        disabled: {
          primary: "#E9E9F3",
          black: "#BABAC2",
        },
      },
      lineHeight: {
        1: "1",
      },
      boxShadow: {
        lg: "0 2px 30px rgba(4, 28, 35, .1)",
        xl: "0 3rem 6rem -1rem rgba(0, 0, 0, 0.075)",
        btn: "0 2px 20px 3px rgba(0,187,255, .12)",
        "btn-secondary": "inset 0 0 0 2px rgb(0,187,255)",
        purple: "0 2px 20px 3px rgba(98,93,213, .12)",
        green: "0 2px 20px 3px rgba(90,245,209, .12)",
        success: "0 2px 12px rgba(76, 248, 208, .3)",
        slider: "0 5px 40px -10px rgba(76, 248, 208, .06)",
      },
      transitionDuration: {
        0: "0",
        250: "250ms",
        300: "300ms",
        400: "400ms",
        600: "600ms",
        800: "800ms",
      },
      transitionDelay: {
        350: "350ms",
        600: "600ms",
      },
      zIndex: {
        "-1": "-1",
        1: "1",
        2: 2,
        999: 999,
      },
      width: {
        "10p": "10%",
        "15p": "15%",
        "20p": "20%",
        "25p": "25%",
        "30p": "30%",
        "35p": "35%",
        "40p": "40%",
        "45p": "45%",
        "50p": "50%",
        "55p": "55%",
        "60p": "60%",
        "65p": "65%",
        "70p": "70%",
        "75p": "75%",
        "80p": "80%",
        "85p": "85%",
        "90p": "90%",
        "95p": "95%",
        "10v": "10vw",
        "20v": "20vw",
        "30v": "30vw",
        "35v": "35vw",
        "40v": "40vw",
        "45v": "45vw",
        "50v": "50vw",
        "55v": "55vw",
        "60v": "60vw",
        "70v": "70vw",
        "80v": "80vw",
        "85v": "85vw",
        "90v": "90vw",
        screen: "100vw",
      },
      minWidth: {
        1: "1rem",
        2: "2rem",
        3: "3rem",
        4: "4rem",
        5: "5rem",
        6: "6rem",
        7: "7rem",
        8: "8rem",
        9: "9rem",
        10: "10rem",
        logo: "9rem",
        screen: "100vw",
      },
      maxWidth: {
        1: "1rem",
        1.5: "1.5rem",
        2: "2rem",
        3: "3rem",
        4: "4rem",
        5: "5rem",
        6: "6rem",
        7: "7rem",
        8: "8rem",
        9: "9rem",
        10: "10rem",
        logo: "9rem",
        screen: "100vw",
      },
      height: {
        "10v": "10vh",
        "15v": "15vh",
        "20v": "20vh",
        "25v": "25vh",
        "30v": "30vh",
        "35v": "35vh",
        "40v": "40vh",
        "45v": "45vh",
        "50v": "50vh",
        "55v": "55vh",
        "60v": "60vh",
        "65v": "65vh",
        "70v": "70vh",
        "73v": "73vh",
        "75v": "75vh",
        "80v": "80vh",
        "85v": "85vh",
        "90v": "90vh",
        "95v": "95vh",
        "h-1/2": "50%",
        "h-1/3": "33.333333%",
        "h-2/3": "66.666667%",
        "h-1/4": "25%",
        "h-2/4": "50%",
        "h-3/4": "75%",
        "h-1/5": "20%",
        "h-2/5": "40%",
        "h-3/5": "60%",
        "h-4/5": "80%",
        "h-1/6": "16.666667%",
        "h-2/6": "33.333333%",
        "h-3/6": "50%",
        "h-4/6": "66.666667%",
        "h-5/6": "83.333333%",
        "10p": "10%",
        "15p": "15%",
        "20p": "20%",
        "25p": "25%",
        "30p": "30%",
        "35p": "35%",
        "40p": "40%",
        "45p": "45%",
        "50p": "50%",
        "55p": "55%",
        "60p": "60%",
        "65p": "65%",
        "70p": "70%",
        "75p": "75%",
        "80p": "80%",
        "85p": "85%",
        "90p": "90%",
        "95p": "95%",
      },
      maxHeight: {
        1: "1rem",
        2: "2rem",
        3: "3rem",
        4: "4rem",
        5: "5rem",
        6: "6rem",
        7: "7rem",
        8: "8rem",
        9: "9rem",
        10: "10rem",
        logo: "3rem",
        screen: "100vh",
      },
      inset: {
        4: "1rem",
        "1/2": "50%",
        "-1/2": "-50%",
        100: "100%",
        "-100": "-100%",
      },
      translate: {
        "1/2": "50%",
        "-1/2": "-50%",
      },
      margin: {
        "1/2": "50%",
        "-1/2": "-50%",
        100: "100%",
        "1/5": "20%",
        "2/5": "40%",
        "3/5": "60%",
        "4/5": "80%",
        "1/12": "8.3333%",
        "2/12": "16.6666%",
        "3/12": "25%",
        "4/12": "33.3333%",
        "5/12": "41.6666%",
        "6/12": "50%",
        "7/12": "58.3333%",
        "8/12": "66.6666%",
        "9/12": "75%",
        "10/12": "83.3333%",
        "11/12": "91.6666%",
        "-100": "-100%",
        screen20: "20vh",
        screen25: "25vh",
        screen30: "30vh",
        screen35: "35vh",
        screen40: "40vh",
        screen45: "45vh",
        screen50: "50vh",
        screen55: "55vh",
        screen60: "60vh",
        screen65: "65vh",
        screen70: "70vh",
        screen75: "75vh",
        screen80: "80vh",
        screen85: "85vh",
        screen90: "90vh",
        screen95: "95vh",
        screen: "100vh",
      },
    },
  },
  variantOrder: [
    "first",
    "last",
    "odd",
    "even",
    "visited",
    "checked",
    "group-hover",
    "group-focus",
    "focus-within",
    "hover",
    "focus",
    "focus-visible",
    "active",
    "group-disabled", // Custom variant
    "disabled",
  ],
  variants: {
    accessibility: [
      "responsive",
      "focus-within",
      "focus",
      "disabled",
      "active",
    ],
    alignContent: ["responsive", "disabled", "active"],
    alignItems: ["responsive", "disabled", "active"],
    alignSelf: ["responsive", "disabled", "active"],
    animation: ["responsive", "disabled", "active"],
    appearance: ["responsive", "disabled", "active"],
    backgroundAttachment: ["responsive", "disabled", "active"],
    backgroundClip: ["responsive", "disabled", "active"],
    backgroundColor: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    backgroundImage: ["responsive", "active"],
    backgroundOpacity: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    backgroundPosition: ["responsive", "disabled", "active"],
    backgroundRepeat: ["responsive", "disabled", "active"],
    backgroundSize: ["responsive", "disabled", "active"],
    borderCollapse: ["responsive", "disabled", "active"],
    borderColor: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    borderOpacity: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    borderRadius: ["responsive", "disabled", "active"],
    borderStyle: ["responsive", "disabled", "active"],
    borderWidth: ["responsive", "disabled", "active"],
    boxShadow: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    boxSizing: ["responsive", "disabled", "active"],
    clear: ["responsive", "disabled", "active"],
    container: ["responsive", "disabled", "active"],
    cursor: ["responsive", "disabled", "active"],
    display: ["responsive", "disabled", "active"],
    divideColor: ["responsive", "disabled", "active"],
    divideOpacity: ["responsive", "disabled", "active"],
    divideStyle: ["responsive", "disabled", "active"],
    divideWidth: ["responsive", "disabled", "active"],
    fill: ["responsive", "disabled", "active"],
    flex: ["responsive", "disabled", "active"],
    flexDirection: ["responsive", "disabled", "active"],
    flexGrow: ["responsive", "disabled", "active"],
    flexShrink: ["responsive", "disabled", "active"],
    flexWrap: ["responsive", "disabled", "active"],
    float: ["responsive", "disabled", "active"],
    fontFamily: ["responsive", "disabled", "active"],
    fontSize: ["responsive", "disabled", "active"],
    fontSmoothing: ["responsive", "disabled", "active"],
    fontStyle: ["responsive", "disabled", "active"],
    fontVariantNumeric: ["responsive", "disabled", "active"],
    fontWeight: ["responsive", "disabled", "active"],
    gap: ["responsive", "disabled", "active"],
    gradientColorStops: ["responsive", "hover", "focus", "disabled", "active"],
    gridAutoColumns: ["responsive", "disabled", "active"],
    gridAutoFlow: ["responsive", "disabled", "active"],
    gridAutoRows: ["responsive", "disabled", "active"],
    gridColumn: ["responsive", "disabled", "active"],
    gridColumnEnd: ["responsive", "disabled", "active"],
    gridColumnStart: ["responsive", "disabled", "active"],
    gridRow: ["responsive", "disabled", "active"],
    gridRowEnd: ["responsive", "disabled", "active"],
    gridRowStart: ["responsive", "disabled", "active"],
    gridTemplateColumns: ["responsive", "disabled", "active"],
    gridTemplateRows: ["responsive", "disabled", "active"],
    height: ["responsive", "disabled", "active"],
    inset: ["responsive", "disabled", "active"],
    justifyContent: ["responsive", "disabled", "active"],
    justifyItems: ["responsive", "disabled", "active"],
    justifySelf: ["responsive", "disabled", "active"],
    letterSpacing: ["responsive", "disabled", "active"],
    lineHeight: ["responsive", "disabled", "active"],
    listStylePosition: ["responsive", "disabled", "active"],
    listStyleType: ["responsive", "disabled", "active"],
    margin: ["responsive", "disabled", "active"],
    maxHeight: ["responsive", "disabled", "active"],
    maxWidth: ["responsive", "disabled", "active"],
    minHeight: ["responsive", "disabled", "active"],
    minWidth: ["responsive", "disabled", "active"],
    objectFit: ["responsive", "disabled", "active"],
    objectPosition: ["responsive", "disabled", "active"],
    opacity: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    order: ["responsive", "disabled"],
    outline: ["responsive", "focus-within", "focus", "disabled", "active"],
    overflow: ["responsive", "disabled"],
    overscrollBehavior: ["responsive", "disabled", "active"],
    padding: ["responsive", "disabled"],
    placeContent: ["responsive", "disabled", "active"],
    placeItems: ["responsive", "disabled", "active"],
    placeSelf: ["responsive", "disabled", "active"],
    placeholderColor: ["responsive", "focus", "disabled", "active"],
    placeholderOpacity: ["responsive", "focus", "disabled", "active"],
    pointerEvents: ["responsive", "disabled", "active"],
    position: ["responsive", "disabled", "active"],
    resize: ["responsive", "disabled"],
    ringColor: ["responsive", "focus-within", "focus", "disabled", "active"],
    ringOffsetColor: [
      "responsive",
      "focus-within",
      "focus",
      "disabled",
      "active",
    ],
    ringOffsetWidth: [
      "responsive",
      "focus-within",
      "focus",
      "disabled",
      "active",
    ],
    ringOpacity: ["responsive", "focus-within", "focus", "disabled", "active"],
    ringWidth: ["responsive", "focus-within", "focus", "disabled", "active"],
    rotate: ["responsive", "hover", "focus", "disabled", "active"],
    scale: ["responsive", "hover", "focus", "disabled", "active"],
    skew: ["responsive", "hover", "focus", "disabled", "active"],
    space: ["responsive", "disabled", "active"],
    stroke: ["responsive", "disabled", "active"],
    strokeWidth: ["responsive", "disabled", "active"],
    tableLayout: ["responsive", "disabled", "active"],
    textAlign: ["responsive", "disabled", "active"],
    textColor: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    textDecoration: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    textOpacity: [
      "responsive",
      "group-hover",
      "focus-within",
      "hover",
      "focus",
      "disabled",
      "active",
    ],
    textOverflow: ["responsive", "disabled", "active"],
    textTransform: ["responsive", "disabled", "active"],
    transform: ["responsive", "disabled", "active"],
    transformOrigin: ["responsive", "disabled", "active"],
    transitionDelay: ["responsive", "disabled", "active"],
    transitionDuration: ["responsive", "disabled", "active"],
    transitionProperty: ["responsive", "disabled", "active"],
    transitionTimingFunction: ["responsive", "disabled", "active"],
    translate: ["responsive", "hover", "focus", "disabled", "active"],
    userSelect: ["responsive", "disabled", "active"],
    verticalAlign: ["responsive", "disabled", "active"],
    visibility: ["responsive", "disabled", "active"],
    whitespace: ["responsive", "disabled", "active"],
    width: ["responsive", "disabled", "active"],
    wordBreak: ["responsive", "disabled", "active"],
    zIndex: ["responsive", "focus-within", "focus", "disabled", "active"],
  },
  plugins: [
    plugin(function ({ addComponents, addBase, config }) {
      addBase({
        h1: { fontSize: config("theme.fontSize.6xl") },
        h2: { fontSize: config("theme.fontSize.5xl"), marginBottom: "1.2rem" },
        h3: { fontSize: config("theme.fontSize.lg") },
        "h1,h2,h3,h4,h5,h6": { fontWeight: "900", lineHeight: "1.25" },
        a: { color: config("theme.colors.primary.500") },
        strong: { fontWeight: "900" },
        p: { marginBottom: "1rem" },
        ".container": { padding: "0 1rem" },
      });
      const extraComponents = {
        ".arrow-right": {
          width: "20px",
          height: "0",
          backgroundColor: "#fff",
          display: "inline-block",
          position: "relative",
          transition: "all .2s ease",
          marginLeft: ".5rem",
          borderTop: "1px solid",
          borderBottom: "1px solid",
          "&:after": {
            content: '""',
            position: "absolute",
            right: "0",
            width: "8px",
            height: "8px",
            borderRight: "2px solid",
            borderBottom: "2px solid",
            transform: "rotate(-45deg)",
            top: "50%",
            marginTop: "-4px",
          },
        },
        a: {
          "&:hover": {
            ".arrow-right": {
              transform: "translateX(3px)",
            },
          },
        },
        ".success--check": {
          width: "30px",
          height: "30px",
          background: config("theme.colors.green.500"),
          borderRadius: "100%",
          position: "relative",
          boxShadow: config("theme.boxShadow.success"),

          "&:after": {
            content: '""',
            width: "7px",
            height: "14px",
            borderRight: "2px solid",
            borderBottom: "2px solid",
            borderColor: "white",
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "rotate(45deg)",
            marginTop: "-8px",
            marginLeft: "-3px",
          },
        },
        ".overlay": {
          position: "relative",
          zIndex: "1",
          "&:after": {
            content: '""',
            position: "absolute",
            top: "0",
            left: "0",
            width: "100%",
            height: "100%",
            background: config("theme.colors.dark.900"),
            opacity: ".8",
            zIndex: "-1",
          },
        },
        ".checked": {
          width: ".5rem",
          height: ".9rem",
          borderRight: "2px solid",
          borderBottom: "2px solid",
          borderColor: "white",
          transform: "rotate(45deg)",
          position: "relative",
          bottom: "2px",
        },
        ".pending": {
          textAlign: "center",
          "&:after": {
            content: '"..."',
            fontSize: "1.75rem",
            color: "white",
            lineHeight: "1",
            position: "absolute",
            left: "50%",
            top: "50%",
            marginTop: "-.82rem",
            marginLeft: "-.4rem",
          },
        },
      };

      addComponents([extraComponents]);
    }),
  ],
};
